### PR TITLE
Add docs on MethodInstances

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Odd...CI passed on #4, #5, and #6. I wonder what went wrong here?

**Comment by timholy** [comment]
Still failing. The issue is that `Base.ocachefile_from_cachefile(path)` is not returning the correct path to the `.so` cache file. From the debug commit log:

```julia
path = "/home/runner/.julia/compiled/v1.10/Colors/NKjaT_t9hk1.ji"
isfile(path) = true
opath = "/home/runner/.julia/compiled/v1.10/Colors/NKjaT_t9hk1.so"
isfile(opath) = false
```

Any ideas, @vchuravy?

**Comment by timholy** [comment]
I should say it works fine locally, this seems to be a CI-specific issue.

**Comment by vchuravy** [comment]
Are you sure that code-coverage is not turned on?

**Comment by IanButterworth** [comment]
julia-runtest defaults to coverage on, so it should be based on the test yml

**Comment by timholy** [comment]
Fixed in #11

**Comment by timholy** [comment]
Registration is underway, but apparently JuliaRegistrator is not ready for the `weakdeps` world. There may be a bit of a delay.

Until then, we should periodically check and see if https://timholy.github.io/PkgCacheInspector.jl/dev/ eventually deploys (it hasn't yet at the time of this writing).

**Comment by timholy** [comment]
Hmm, still no docs. Any ideas?

**Comment by IanButterworth** [comment]
No idea

**Comment by timholy** [comment]
Fixed, problem was in the Pages setting:
image

Under `Branch` it needs to be `gh-pages` and `/(root)`

**Comment by timholy** [comment]
Fix is thanks to @mortenpi

**Pull request merged**
