### PR TITLE
Bump version to v1.0.1

### PR DESCRIPTION
**Pull request by fatteneder**
In order to make the fix #18 available.

### CODE REVIEW

**Comment by IanButterworth** [comment]
https://github.com/JuliaRegistries/General/pull/106291

**Comment by fatteneder** [comment]
Thanks Ian!

**Comment by IanButterworth** [comment]
Looking at the PRs on the release this probably should've been a minor release, but no harm 
https://github.com/timholy/PkgCacheInspector.jl/releases/tag/v1.0.1

**Comment by fatteneder** [comment]
Oh, I see.
Given that there is still a problem with the #18 fix here https://github.com/JuliaLang/julia/issues/53570#issuecomment-2096980550, we might have to make a another release anyways.

**Pull request merged**
